include: package:lints/recommended.yaml

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_unnamed_constructors_first: true
    super_goes_last: true
    recursive_getters: false
    prefer_relative_imports: true
    prefer_const_constructors: true