name: syntax_analyzer
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  lexical_analyzer2:
    git: https://github.com/mitryp/lexical_analyzer

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
